# docker-compose.yml for Syndicate CI testing

version: '2'

services:
  syndicate-base:
    build: . 
    dockerfile: Dockerfile.base

  syndicate-ms:
    build: .
    dockerfile: Dockerfile.ms
    expose:
        - "8080"
    volumes:
      - ./ms/app.yaml:/usr/src/syndicate/ms/app.yaml
      - ./ms/admin_info.py:/usr/src/syndicate/ms/common/admin_info.py

