# docker-compose.yml for Syndicate CI testing

version: '2'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: syndicate-ci-test
    depends_on:
      - ms
    links:
      - ms
    volumes:
      - ../run_syndicate_tests.sh:/opt/run_syndicate_tests.sh:ro
      - ../tests:/opt/tests:ro
      - ../results:/opt/results

  ms:
    build:
      context: .
      dockerfile: Dockerfile.ms
    image: syndicate-ci-ms
    expose:
      - "8080"
    volumes:
      - ./ms/app.yaml:/usr/src/syndicate/ms/app.yaml:ro

